ORDER = [
    'Art',
    'History',
    'Philosophy',
    'Biology',
    'Chemistry',
    'Computer science',
    'Environmental science',
    'Engineering',
    'Geography',
    'Geology',
    'Materials science',
    'Mathematics',
    'Medicine',
    'Physics',
    'Business',
    'Economics',
    'Political science',
    'Psychology',
    'Sociology',
]

JOURNAL_MAP = {
    'Nature Reviews Molecular Cell Biology': ["nat. rev. mol. cell biol.", "nat rev mol cell biol", "nature reviews molecular cell biology"],
    'Cell': ["cell", "cell press"],
    'Research Papers in Economics': ["repec", "research papers in economics"],
    "Nature": ["nature"],
    "Proceedings of the National Academy of Sciences of the United States of America": ["pnas", "proceedings of the national academy of sciences", "proceedings of the national academy of sciences of the united states of america"],
    "The New England Journal of Medicine": ["n engl j med", "n. engl. j. med.", "nejm", "new england journal of medicine", "the new england journal of medicine"],
    'Applied Physics Letters': ["appl. phys. lett.", "appl phys lett", "applied physics letters"],
    "Science": ["science"],
    "Journal of the American Chemical Society": ["journal of the american chemical society", "j. am. chem. soc.", "jacs", "j am chem soc"],
    'Angewandte Chemie': ["angew. chem. int. ed.", "angew chem int ed", "angewandte chemie", "angewandte chemie international edition"], 
    'JAMA': ["jama", "jama network", "jama network open"],
    "Physical Review Letters": ["physical review letters", "phys. rev. lett.", "phys rev lett", "prl"],
    'Nature Reviews Cancer': ["nat. rev. cancer", "nat rev cancer", "nature reviews cancer"],
    'Chemical Reviews': ["chem. rev.", "chem rev", "chemical reviews", "chemical reviews journal"],
    'The Lancet': ["lancet", "the lancet"],
    "PLOS ONE": ["plos one"],
    'Circulation': ["circulation", "circulation research"],
    'Nature Materials': ["nat. mater.", "nat mater", "nature materials"],
    'Physical Review B': ["phys. rev. b", "phys rev b", "physical review b"],
    'Journal of Chemical Physics': ["j. chem. phys.", "j chem phys", "journal of chemical physics", "the journal of chemical physics"],
    "Journal of Biological Chemistry": ["the journal of biological chemistry", "journal of biological chemistry", "j. biol. chem.", "j biol chem", "jbc"],
    "Journal of Applied Physics": ["j. appl. phys.", "j appl phys", "journal of applied physics"],
    "The Astrophysical Journal": ["the astrophysical journal", "astrophysical journal", "apj", "astrophys j", "astrophys. j."],
    "Chemical Society Reviews": ["chem. soc. rev.", "chem soc rev", "chemical society reviews"],
}